# Generated by Django 4.1.2 on 2023-11-20 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buerger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('profileimg', models.ImageField(default='/home/ubuntu/website/virtualgovservices/pictures/proflie_images/avatar.jpg', upload_to='virtualgovservices/pictures/profile_images')),
                ('anrede', models.CharField(max_length=10)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('strasse', models.CharField(max_length=100)),
                ('postleitzahl', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('telefonnummer', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('geburtsdatum', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hundeanmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angemeldet_am', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.IntegerField()),
                ('anrede', models.CharField(max_length=10)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('strasse', models.CharField(max_length=100)),
                ('postleitzahl', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('telefonnummer', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('geburtsdatum', models.DateField()),
                ('buerger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='virtualgovservices.buerger')),
            ],
        ),
    ]
