# Generated by Django 4.1.2 on 2023-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buerger',
            name='geburtsdatum',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='buerger',
            name='profileimg',
            field=models.ImageField(default='/home/ubuntu/website/static/virtualgovservices/pictures/proflie_images/avatar.jpg', upload_to='virtualgovservices/pictures/profile_images'),
        ),
    ]
