# Generated by Django 4.1.2 on 2023-11-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0003_alter_buerger_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buerger',
            name='profileimg',
            field=models.ImageField(default='/static/virtualgovservices/pictures/profile_images/avatar.jpg', upload_to='virtualgovservices/pictures/profile_images'),
        ),
    ]
