# Generated by Django 4.1.2 on 2023-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0004_alter_buerger_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buerger',
            name='profileimg',
            field=models.ImageField(default='/home/ubuntu/website/media/virtualgovservices/profile_images/avatar.jpg', upload_to='virtualgovservices/pictures/profile_images'),
        ),
    ]
