# Generated by Django 4.1.2 on 2023-11-28 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtualgovservices', '0006_alter_buerger_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buerger',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='anrede',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='geburtsdatum',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='nachname',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='postleitzahl',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='strasse',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='telefonnummer',
        ),
        migrations.RemoveField(
            model_name='hundeanmeldung',
            name='vorname',
        ),
        migrations.AlterField(
            model_name='buerger',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='buerger',
            name='profileimg',
            field=models.ImageField(default='/virtualgovservices/profile_images/avatar.jpg', upload_to='virtualgovservices/profile_images/'),
        ),
        migrations.AlterField(
            model_name='hundeanmeldung',
            name='buerger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hundeanmeldungen', to='virtualgovservices.buerger'),
        ),
        migrations.CreateModel(
            name='Verfahren',
            fields=[
                ('nummer', models.AutoField(primary_key=True, serialize=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('zustand', models.CharField(max_length=100)),
                ('themengebiet', models.CharField(max_length=100)),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verfahren', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(unique=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('digital_signatur', models.TextField()),
                ('inhalt', models.TextField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
                ('verfahren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='virtualgovservices.verfahren')),
            ],
        ),
    ]
