# Generated by Django 4.1.2 on 2023-11-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0007_remove_buerger_id_user_remove_hundeanmeldung_anrede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='hundeanmeldung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='virtualgovservices.hundeanmeldung'),
        ),
        migrations.AddField(
            model_name='hundeanmeldung',
            name='verfahren',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualgovservices.verfahren'),
        ),
    ]
