# Generated by Django 4.1.2 on 2023-12-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0008_dokument_hundeanmeldung_hundeanmeldung_verfahren'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beamter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='dokument',
            old_name='digital_signatur',
            new_name='digitale_signatur',
        ),
        migrations.AlterField(
            model_name='verfahren',
            name='zustand',
            field=models.CharField(default='Eingegangen', max_length=100),
        ),
    ]
