# Generated by Django 4.1.2 on 2023-12-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0009_beamter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='digitale_signatur',
            field=models.TextField(blank=True),
        ),
    ]
