# Generated by Django 4.1.2 on 2023-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0010_alter_dokument_digitale_signatur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='uri',
            field=models.TextField(unique=True),
        ),
    ]
