# Generated by Django 4.1.2 on 2023-12-12 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtualgovservices', '0011_dokument_url_alter_dokument_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='verfahren',
            name='antragssteller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verfahren',
            name='verantwortlicher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualgovservices.beamter'),
        ),
    ]
