# Generated by Django 4.1.2 on 2023-12-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0012_verfahren_antragssteller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verfahren',
            name='antragssteller',
        ),
    ]
