# Generated by Django 4.1.2 on 2023-12-12 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtualgovservices', '0014_remove_verfahren_verantwortlicher'),
    ]

    operations = [
        migrations.AddField(
            model_name='verfahren',
            name='verantwortlicher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
