# Generated by Django 4.1.2 on 2023-12-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0016_verfahren_antragssteller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hundeanmeldung',
            name='datum_haltung_hund',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hundeanmeldung',
            name='geschlecht_hund',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hundeanmeldung',
            name='kampfhund',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hundeanmeldung',
            name='name_hund',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hundeanmeldung',
            name='rasse_hund',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hundeanmeldung',
            name='wurftag_hund',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='hundeanmeldung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualgovservices.hundeanmeldung'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='verfahren',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualgovservices.verfahren'),
        ),
    ]
