# Generated by Django 4.1.2 on 2023-12-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0017_hundeanmeldung_datum_haltung_hund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='hundeanmeldung',
        ),
        migrations.AddField(
            model_name='hundeanmeldung',
            name='dokument',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualgovservices.dokument'),
        ),
    ]
