# Generated by Django 4.1.2 on 2023-12-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0018_remove_dokument_hundeanmeldung_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hundeanmeldung',
            old_name='datum_haltung_hund',
            new_name='beginn_haltung_hund',
        ),
    ]
