# Generated by Django 4.1.2 on 2023-12-19 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtualgovservices', '0019_rename_datum_haltung_hund_hundeanmeldung_beginn_haltung_hund'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamter',
            name='anrede',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beamter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='beamter',
            name='nachname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beamter',
            name='telefonnummer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beamter',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beamter',
            name='vorname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beamter',
            name='zuständigkeit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
