# Generated by Django 4.1.2 on 2023-12-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0022_alter_verfahren_verantwortlicher'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamter',
            name='nr_zuständigkeit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
