# Generated by Django 4.1.2 on 2024-01-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0024_alter_verfahren_zustand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buerger',
            name='geburtsdatum',
            field=models.DateField(blank=True, default='1980-01-01'),
        ),
    ]
