# Generated by Django 4.1.2 on 2024-01-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0026_alter_buerger_geburtsdatum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wohnsitzanmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angemeldet_am', models.DateTimeField(auto_now_add=True)),
                ('umzugsdatum', models.DateField()),
                ('neue_strasse', models.CharField(max_length=100)),
                ('neue_postleitzahl', models.CharField(max_length=10)),
                ('neuer_ort', models.CharField(max_length=100)),
                ('vorherige_adresse', models.CharField(blank=True, max_length=100)),
                ('buerger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualgovservices.buerger')),
                ('dokument', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualgovservices.dokument')),
                ('verfahren', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualgovservices.verfahren')),
            ],
        ),
    ]
