# Generated by Django 4.1.2 on 2024-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualgovservices', '0027_wohnsitzanmeldung'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamter',
            name='raum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beamter',
            name='rolle',
            field=models.CharField(choices=[('beamter', 'Beamter')], default='beamter', max_length=10),
        ),
        migrations.AddField(
            model_name='buerger',
            name='rolle',
            field=models.CharField(choices=[('buerger', 'Bürger')], default='buerger', max_length=10),
        ),
    ]
